---
development:
  cloud_name: li9udtn2b
  api_key: '931591874922263'
  api_secret: xkzRFGavdAs8zHs8SMQdM0EqjNU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: li9udtn2b
  api_key: '931591874922263'
  api_secret: xkzRFGavdAs8zHs8SMQdM0EqjNU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: li9udtn2b
  api_key: '931591874922263'
  api_secret: xkzRFGavdAs8zHs8SMQdM0EqjNU
  enhance_image_tag: true
  static_image_support: false