development:
  adapter: postgresql
  encoding: unicode
  database: facelift_development
  pool: 5
  username: facelift_administrator
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: facelift_test
  pool: 5
  username: facelift_administrator
  password: